# fly.toml app configuration file generated for velut on 2023-09-22T19:21:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "velut"
kill_signal = "SIGINT"
kill_timeout = "10s"
primary_region = "lhr"
swap_size_mb = 512

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  auto_stop_machines = "stop"
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 16
    soft_limit = 10

  [[services.http_checks]]
    interval = "15s"
    timeout = "20s"
    grace_period = "60s"
    path = "/healthcheck"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "15s"
    path = "/healthcheck"
