import {
  Details,
  getTabForCurrentWord,
  getTabsId,
  LatinLinksOrPlainText,
} from './FormsTable'
import Tabs from './Tabs'
import styles from './FormsTable.module.css'

const TableForSomeVerbForms = ({
  formsFromWordsCollection,
  Forms,
  linkBase,
  currentWordHyphenated,
}) => {
  const generateLatinLinksOrPlainText = (formsArray) => (
    <LatinLinksOrPlainText
      formsArray={formsArray}
      formsFromWordsCollection={formsFromWordsCollection}
      linkBase={linkBase}
      currentWordHyphenated={currentWordHyphenated}
    />
  )
  return (
    <>
      <table>
        <thead>
          <tr>
            <th rowSpan="2" colSpan="2">
              indicative
            </th>
            <th colSpan="3">singular</th>
            <th colSpan="3">plural</th>
          </tr>
          <tr>
            <th>first</th>
            <th>second</th>
            <th>third</th>
            <th>first</th>
            <th>second</th>
            <th>third</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th rowSpan="6">active</th>
            <th>present</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.present.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.present.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.present.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.present.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.present.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.present.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>imperfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.imperfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.imperfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.imperfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.imperfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.imperfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.imperfect.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>future</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.future.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.future.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.future.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.future.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.future.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.future.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>perfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.perfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.perfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.perfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.perfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.perfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.perfect.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>pluperfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.pluperfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.pluperfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.pluperfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.pluperfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.pluperfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.pluperfect.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>future perfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.futureperfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.futureperfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.futureperfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.futureperfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.futureperfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.active.futureperfect.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th rowSpan="3">passive</th>
            <th>present</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.present.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.present.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.present.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.present.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.present.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.present.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>imperfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.imperfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.imperfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.imperfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.imperfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.imperfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.imperfect.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>future</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.future.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.future.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.future.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.future.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.future.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.indicative.passive.future.plural.third,
              )}
            </td>
          </tr>
        </tbody>
      </table>

      <table>
        <thead>
          <tr>
            <th rowSpan="2" colSpan="2">
              subjunctive
            </th>
            <th colSpan="3">singular</th>
            <th colSpan="3">plural</th>
          </tr>
          <tr>
            <th>first</th>
            <th>second</th>
            <th>third</th>
            <th>first</th>
            <th>second</th>
            <th>third</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th rowSpan="4">active</th>
            <th>present</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.present.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.present.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.present.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.present.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.present.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.present.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>imperfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.imperfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.imperfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.imperfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.imperfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.imperfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.imperfect.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>perfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.perfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.perfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.perfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.perfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.perfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.perfect.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>pluperfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.pluperfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.pluperfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.pluperfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.pluperfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.pluperfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.active.pluperfect.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th rowSpan="2">passive</th>
            <th>present</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.present.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.present.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.present.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.present.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.present.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.present.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>imperfect</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.imperfect.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.imperfect.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.imperfect.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.imperfect.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.imperfect.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.subjunctive.passive.imperfect.plural.third,
              )}
            </td>
          </tr>
        </tbody>
      </table>

      <table>
        <thead>
          <tr>
            <th rowSpan="2" colSpan="2">
              imperative
            </th>
            <th colSpan="3">singular</th>
            <th colSpan="3">plural</th>
          </tr>
          <tr>
            <th>first</th>
            <th>second</th>
            <th>third</th>
            <th>first</th>
            <th>second</th>
            <th>third</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th rowSpan="2">active</th>
            <th>present</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.present.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.present.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.present.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.present.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.present.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.present.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>future</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.future.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.future.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.future.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.future.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.future.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.active.future.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th rowSpan="2">passive</th>
            <th>present</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.present.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.present.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.present.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.present.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.present.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.present.plural.third,
              )}
            </td>
          </tr>
          <tr>
            <th>future</th>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.future.singular.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.future.singular.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.future.singular.third,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.future.plural.first,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.future.plural.second,
              )}
            </td>
            <td>
              {generateLatinLinksOrPlainText(
                Forms.imperative.passive.future.plural.third,
              )}
            </td>
          </tr>
        </tbody>
      </table>

      <table>
        <thead>
          <tr>
            <th rowSpan="2">infinitive</th>
            <th colSpan="3">active</th>
            <th colSpan="3">passive</th>
          </tr>
          <tr>
            <th>present</th>
            <th>past</th>
            <th>future</th>
            <th>present</th>
            <th>past</th>
            <th>future</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th></th>
            <td>
              {generateLatinLinksOrPlainText(Forms.infinitive.active.present)}
            </td>
            <td>
              {generateLatinLinksOrPlainText(Forms.infinitive.active.past)}
            </td>
            <td>
              {generateLatinLinksOrPlainText(Forms.infinitive.active.future)}
            </td>
            <td>
              {generateLatinLinksOrPlainText(Forms.infinitive.passive.present)}
            </td>
            <td>
              {generateLatinLinksOrPlainText(Forms.infinitive.passive.past)}
            </td>
            <td>
              {generateLatinLinksOrPlainText(Forms.infinitive.passive.future)}
            </td>
          </tr>
        </tbody>
      </table>

      <table>
        <thead>
          <tr>
            <th rowSpan="2"></th>
            <th colSpan="4">gerund</th>
            <th colSpan="2">supine</th>
          </tr>
          <tr>
            <th>accusative</th>
            <th>genitive</th>
            <th>dative</th>
            <th>ablative</th>
            <th>accusative</th>
            <th>ablative</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th></th>
            <td>{generateLatinLinksOrPlainText(Forms.gerund.accusative)}</td>
            <td>{generateLatinLinksOrPlainText(Forms.gerund.genitive)}</td>
            <td>{generateLatinLinksOrPlainText(Forms.gerund.dative)}</td>
            <td>{generateLatinLinksOrPlainText(Forms.gerund.ablative)}</td>
            <td>{generateLatinLinksOrPlainText(Forms.supine.accusative)}</td>
            <td>{generateLatinLinksOrPlainText(Forms.supine.ablative)}</td>
          </tr>
        </tbody>
      </table>
    </>
  )
}

const VerbFormsTable = ({
  formsFromWordsCollection,
  Forms,
  lemma,
  linkBase,
  currentWordHyphenated,
  openByDefault,
  isFullWidth = true,
  summary = 'All generated forms',
}) => {
  const tabsId = getTabsId({ lemma, summary })

  const classNames = isFullWidth
    ? styles.formsTable + ' ' + styles.fullWidth
    : styles.formsTable

  return (
    <div className={classNames}>
      <Details openByDefault={openByDefault}>
        <summary id={tabsId + '-summary'}>{summary}</summary>
        <Tabs
          id={tabsId}
          ariaLabelledBy={tabsId + '-summary'}
          startTab={getTabForCurrentWord(Forms, currentWordHyphenated)}
        >
          {Forms.unencliticized ? 'Unencliticized' : null}
          {Forms.unencliticized ? (
            <TableForSomeVerbForms
              formsFromWordsCollection={formsFromWordsCollection}
              Forms={Forms.unencliticized}
              linkBase={linkBase}
              currentWordHyphenated={currentWordHyphenated}
            />
          ) : null}
          {Forms.ne ? <span lang="la">-ne</span> : null}
          {Forms.ne ? (
            <TableForSomeVerbForms
              formsFromWordsCollection={formsFromWordsCollection}
              Forms={Forms.ne}
              linkBase={linkBase}
              currentWordHyphenated={currentWordHyphenated}
            />
          ) : null}
          {Forms.que ? <span lang="la">-que</span> : null}
          {Forms.que ? (
            <TableForSomeVerbForms
              formsFromWordsCollection={formsFromWordsCollection}
              Forms={Forms.que}
              linkBase={linkBase}
              currentWordHyphenated={currentWordHyphenated}
            />
          ) : null}
          {Forms.ve ? <span lang="la">-ve</span> : null}
          {Forms.ve ? (
            <TableForSomeVerbForms
              formsFromWordsCollection={formsFromWordsCollection}
              Forms={Forms.ve}
              linkBase={linkBase}
              currentWordHyphenated={currentWordHyphenated}
            />
          ) : null}
        </Tabs>
      </Details>
    </div>
  )
}

export default VerbFormsTable
