import mongoose from 'mongoose'

// The `summary` collection contains one object with the following schema. It was generated by the Inflector (the script that generates inflected forms for every lemma).
const summarySchema = new mongoose.Schema(
  {
    lastUpdatedDate: String,
    inflectorCounts: {
      // Lemmata for which the Inflector generates forms, but not all the forms that were in Excel.
      mismatches: Number,
      // Lemmata for which the Inflector generates all the forms that were in Excel.
      successes: Number,
      // Lemmata for which the Inflector gives no forms, because its functionality is incomplete.
      inflectFuncNotDefined: Number,
      // Lemmata for which the Inflector generates forms, but which are lemmata that are not in the dump of data from Excel.
      noTestData: Number,
      // The total count of lemmata in velut.
      // Should be the sum of mismatches + successes + inflectFuncNotDefined + noTestData.
      // Should also be the sum of toBeManuallyChecked + manuallyChecked.
      total: Number,
      // Lemmata whose forms should be checked manually after being generated by the Inflector.
      toBeManuallyChecked: Number,
      // Lemmata whose forms have been checked manually after being generated by the Inflector.
      // I do this by opening the velut page for the lemma locally (eg localhost:3000/exemplum) and confirming that the generated forms are as I want them.
      manuallyChecked: Number,
    },
    // This is the list of all lemmata that had forms in Excel that have been deemed to be incorrect while making the Inflector.
    // Therefore, the forms are on the live website, but will ultimately be removed when the production database is switched to using the forms generated by the Inflector, not the forms that were in Excel.
    errata: [
      {
        lemma: String,
        incorrectForms: [String],
      },
    ],
  },
  { collection: 'summary' },
)

//// If Summary is already on the Mongoose model, we use it, otherwise add it.
export default mongoose.models?.summary || mongoose.model('summary', summarySchema)
